version: '3.8'
services:
    mysql:
        hostname: mysql
        image: mariadb:10.5
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=workshop_register
            - MYSQL_USER=main
            - MYSQL_PASSWORD=password
        volumes:
            - mysql-data:/var/lib/mysql:rw
        ports:
            - 3307:3306
        networks:
            - workshop-registration-network

    workshop-registration:
        hostname: workshop-registration
        # working_dir: /var/www/workshop-registration
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./.env:/var/www/workshop-registration/.env:rw
        ports:
            - 8070:80
        networks:
            - workshop-registration-network

volumes:
    mysql-data:

networks:
    workshop-registration-network: