version: '3.7'
services:
    mysql8:
        image: mysql:8
        container_name: mysql8-workshop-register
        ports:
            - '3308:3306'
        volumes:
            - mysql-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: workshop_register
        networks:
            - nginx-php74-mysql8
    php74:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php74-workshop-register
        ports:
            - "9001:9000"
        volumes:
            - ./symfony:/var/www/workshop-register
        networks:
            - nginx-php74-mysql8
    
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-workshop-register
        ports:
            - "8070:80"
        volumes:
            - ./symfony:/var/www/workshop-register
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74
            - mysql8
        networks:
            - nginx-php74-mysql8


networks:
    nginx-php74-mysql8:

volumes:
    mysql-data: